name: run-docker
on:
  push:
    tags:
      - 'v*'
jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: run docker step
        id: run-docker
        uses: ./run-docker-action
